### ISSUE TITLE
Langstone RX with RTL SDR

### ISSUE THREAD

**Issue by f4dvk** [g4eml/Langstone-V2#15]
Hello,

Is it possible to support RTL SDR key in RX only ?
This can be interesting, also with direct sampling for HF reception.

Thanks,
Stephane.

**Comment by g4eml** [comment]
Hello Stephane,Langstone was written as a transceiver, so it expects Tx hardware to be available. The GNURadio code would not work without Tx. Whilst it might be possible to disable the Tx code it would need a lot of work , and I don't have the time available to do that. Colin On 19 Oct 2024 12:07, f4dvk ***@***.***> wrote:
Hello,
Is it possible to support RTL SDR key in RX only ?
This can be interesting, also with direct sampling for HF reception.
Thanks,
Stephane.

**Comment by f4dvk** [comment]
Thank you Colin,

Langstone has a nice interface and could fit a simple receiver with an RTL key.
The idea is launched ;-).

Stephane.
