### ISSUE TITLE
Could we use the native (HDMI) screen as the framebuffer?

### ISSUE THREAD

**Issue by g4wsz** [g4eml/Langstone-V2#5]
I'm just trying to test out Langstone on a Pi4 that doesn't (yet) have a display panel attached.  For testing, it would be useful to be able to see the display image on an HDMI monitor, is this possible?  I can see that Langstone has created a regular file called /dev/fb0 so perhaps this could be done, maybe with something like a VNC framebuffer?

**Comment by g4eml** [comment]
I have never tried it.  Langstone is designed to work only with the recommended displays.



On 12 May 2022, at 12:59, Steve Platt ***@***.***> wrote:

I'm just trying to test out Langstone on a Pi4 that doesn't (yet) have a display panel attached. For testing, it would be useful to be able to see the display image on an HDMI monitor, is this possible? I can see that Langstone has created a regular file called /dev/fb0 so perhaps this could be done, maybe with something like a VNC framebuffer?

**Comment by Montilien** [comment]
Hi,
I installed Langstone-V2 on Pi4 running Lime SDR mini. When I launch Langstone, it return to me "Lang_TRX_Lime.py failed to load".
I checked if the file really exist in Langstone Folder, and it is OK.
Have you some idea about such issue?
73's
F1FHK

**Comment by g4eml** [comment]
Check the log files in the /tmp directory. These should give a clue. 

Make sure that you have a working USB sound module and Lime mini . If either is not working then Lang_TRX_Lime will not run.

**Comment by Montilien** [comment]
It was a non recognized USB audio dongle. I changed it and all goes right.
Regards
________________________________
De : g4eml ***@***.***>
Envoyé : mercredi 28 décembre 2022 12:56
À : g4eml/Langstone-V2 ***@***.***>
Cc : Montilien ***@***.***>; Comment ***@***.***>
Objet : Re: [g4eml/Langstone-V2] Could we use the native (HDMI) screen as the framebuffer? (Issue #5)


Check the log files in the /tmp directory. These should give a clue.

Make sure that you have a working USB sound module and Lime mini . If either is not working then Lang_TRX_Lime will not run.
