### ISSUE TITLE
Pluto segmentation fault

### ISSUE THREAD

**Issue by pe4wj** [g4eml/Langstone-V2#8]
I've done a clean install of Langstone as per the instructions using a new SD card. I've also updated Pluto firmware version v.037. I am using a Pluto RevD. It complains that Lang_tx.py can't find the Pluto, and when I run `Pluto_test` I'm getting a segfault:
![image](https://github.com/g4eml/Langstone/assets/47270032/a878fce0-7d21-4d0b-aaf5-5477be6d863b)

Also reported here as I also get this error when running the original Langstone software: https://github.com/g4eml/Langstone/issues/49
Many thanks in advance for your help!

73,

Wouter Jan PE4WJ

**Comment by g4eml** [comment]
Not a problem with software. Fresh install done here and all working correctly. 
Suggest checking Pluto Power supply.

**Comment by pe4wj** [comment]
For the record: turned out the issue was due to an incorrect firmware update on the Pluto, my Pluto is a RevC and there you have to copy the entire contents of the firmware zip folder onto the USB drive to update it (see the note under "Mass Storage Update" here https://wiki.analog.com/university/tools/pluto/users/firmware ). It works now, thanks Colin!
